language: python
install: gem install fpm
env:
  global:
  - VERSION_NUMBER="`cat package.json | grep version | grep -o '[0-9]\.[0-9]\.[0-9]\+'`"
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: "ErvPkLWvTSoEGaN8Eqd6SuQjyUlZ6fHQKM/FZ3LYXJSX+EhIEQ7hqg5r81ED7ryfOVteh5nMUlrMVxOUhFoslN0lBEeZ7SYkaVrOj08YHEs/BPuET9BtAwx6Y9mJoZ4t+qqmHdg/cknuDKIiK2MT6Tj13VLYVN3Rv399Or+D/JU="
  - REAL_GIT_BRANCH="`git for-each-ref --format='%(objectname) %(refname:short)' refs/heads
    | grep $TRAVIS_COMMIT | awk '{print $2}'`"
before_script:
- echo version_number $VERSION_NUMBER
- echo real_get_branch $REAL_GIT_BRANCH
- echo "deb http://build.openrov.com/debian/ stable debian" | sudo tee -a /etc/apt/sources.list
- echo "deb http://build.openrov.com/debian/ pre-release debian" | sudo tee -a /etc/apt/sources.list
- echo "deb http://build.openrov.com/debian/ development debian" | sudo tee -a /etc/apt/sources.list
- sudo wget -O - -q http://build.openrov.com/debian/build.openrov.com.gpg.key | sudo apt-key add -
- echo "foreign-architecture armhf" | sudo tee -a /etc/dpkg/dpkg.cfg.d/architectures
- sudo cp preferences_$REAL_GIT_BRANCH /etc/apt/preferences
- sudo apt-get update -q  || true
script:
- bash generate_manifest.sh
- bash generate_package.sh
- mkdir stage
- cp manifest ./stage
- cp package.json ./stage
- bash make_package.sh
after_success:
- rm -rf OpenROV/build*
- mkdir build
- DEBFILE="`ls *.deb`""
- cp *.deb build/openrov-onrov-suite_latest-${REAL_GIT_BRANCH}_armhf.deb
- mv *.deb build/
deploy:
  provider: s3
  access_key_id: AKIAIUN4NNHBKIOZE2JA
  secret_access_key:
    secure: FMLP1/dgTDQ2WvrqkXG1ebvtyIBCk7/1pliKitu35zgTmWmP9q0zn3MlcMr/ZURuyjycmYBvRF6NQ/HzYPV4Pp1sjKQ1AEaBQ4cpoRzX5Qc51ae1Yz05kVNLhbxxk9cu2VBwQr9F5VO5moZ3CfXbY5nOWJsJIA+99V9ARNDJ/aM=
  bucket: openrov-software-nightlies
  skip_cleanup: true
  region: us-west-2
  endpoint: bucket-name.s3-website-us-west-2.amazonaws.com
  local-dir: build
  upload-dir: openrov-onrov-suite
  acl: public_read
  on:
    repo: OpenROV/openrov-onrov-suite
    all_branches: true
    condition: "($REAL_GIT_BRANCH = master )||($REAL_GIT_BRANCH = pre-release )||($REAL_GIT_BRANCH = stable)"

notifications:
  webhooks:
    urls:
      - http://build.openrov.com:8080/job/OpenROV-generic-upload-deb-to-repo/buildWithParameters?token=$JENKINS_TOKEN_NAME&urlToDebPackage=http://openrov-software-nightlies.s3-website-us-west-2.amazonaws.com/openrov-onrov-suite%2F$DEBFILE&branch=$REAL_GIT_BRANCH
    on_success: always  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: false     # default: false
